# Generated by Django 6.0.2 on 2026-02-12 08:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education_gpa_experience_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fa-circle', help_text="Font Awesome icon class (e.g., 'fa-camera')", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('professional', 'Professional Working'), ('conversational', 'Conversational'), ('basic', 'Basic')], default='professional', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year', 'order']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', 'order']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', '-proficiency']},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='end_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.AddField(
            model_name='education',
            name='achievements',
            field=models.TextField(blank=True, help_text='Separate achievements with | symbol'),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='fulltime', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, help_text='Leave blank for current', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.CharField(blank=True, help_text='Separate technologies with | symbol', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available for Work'), ('open', 'Open to Opportunities'), ('busy', 'Not Available')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='Detailed professional summary for resume sidebar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.TextField(blank=True, help_text='Separate highlights with | symbol'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('archived', 'Archived')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, help_text='Separate achievements with | symbol'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Separate technologies with | symbol', max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(help_text='Percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory'),
        ),
    ]
